Marc Geremias Serra (2):
      profile_view fet
      modify pre-merge

TheAngel11 (2):
      Merge pull request #21 from claudialajara/timeline_view
      Merge pull request #23 from claudialajara/profile_view

angel.garcia (5):
      Template de header + footer + aside feta
      Preparat entorn de treball per timeline
      Merge conflicts resolved
      Added timeline view
      Added chat view

claudia.lajara (7):
      initial commit
      Basic HOME structure adapted to main layout. Missing complete style. Corrected eslint errors
      Home view listing events finished
      Finished list users view (DISCOVER view)
      Merge conflicts solved for HOME view
      Finished addind filters to Events list (HOME view)
      Added filters to Users list (DISCOVER view)

claudialajara (5):
      Merge pull request #19 from claudialajara/template
      Merge pull request #25 from claudialajara/discover_list_users_view
      Merge pull request #24 from claudialajara/structure_home_main
      Merge pull request #26 from claudialajara/filter_events_view
      Merge pull request #27 from claudialajara/filter_users_view

marcgeremias (1):
      Merge pull request #22 from claudialajara/chat_view

